--- all crates as of v1.8.0
-- @author Alejandro Baez <https://keybase.io/baez>
-- @copyright 2015-2016
-- @license MIT (see LICENSE)
-- @module crates

return {
  "alloc",
  "alloc_jemalloc",
  "alloc_system",
  "arena",
  "backtrace",
  "collections",
  "collectionstest",
  "core",
  "coretest",
  "flate",
  "fmt_macros",
  "getopts",
  "graphviz",
  "libc",
  "log",
  "rand",
  "rbml",
  "rustc",
  "rustc_back",
  "rustc_bitflags",
  "rustc_borrowck",
  "rustc_data_structures",
  "rustc_driver",
  "rustc_front",
  "rustc_lint",
  "rustc_llvm",
  "rustc_metadata",
  "rustc_mir",
  "rustc_passes",
  "rustc_platform_intrinsics",
  "rustc_plugin",
  "rustc_privacy",
  "rustc_resolve",
  "rustc_trans",
  "rustc_typeck",
  "rustc_unicode",
  "rustdoc",
  "serialize",
  "std",
  "syntax",
  "syntax_ext",
  "term",
  "test",
}
