--- all crates as of v1.13.0
-- @author Alejandro Baez <https://keybase.io/baez>
-- @copyright 2014-2016
-- @license MIT (see LICENSE)
-- @module crates

return {
  "alloc",
  "alloc_jemalloc",
  "alloc_system",
  "arena",
  "backtrace",
  "collections",
  "compiler_builtins",
  "core",
  "fmt_macros",
  "getopts",
  "graphviz",
  "libc",
  "panic_abort",
  "panic_unwind",
  "proc_macro",
  "profiler_builtins",
  "rand",
  "rustc",
  "rustc_allocator",
  "rustc_asan",
  "rustc_back",
  "rustc_bitflags",
  "rustc_borrowck",
  "rustc_const_eval",
  "rustc_const_math",
  "rustc_data_structures",
  "rustc_driver",
  "rustc_errors",
  "rustc_incremental",
  "rustc_lint",
  "rustc_llvm",
  "rustc_lsan",
  "rustc_metadata",
  "rustc_mir",
  "rustc_msan",
  "rustc_passes",
  "rustc_platform_intrinsics",
  "rustc_plugin",
  "rustc_privacy",
  "rustc_resolve",
  "rustc_save_analysis",
  "rustc_trans",
  "rustc_tsan",
  "rustc_typeck",
  "rustdoc",
  "serialize",
  "std",
  "std_unicode",
  "syntax",
  "syntax_ext",
  "syntax_pos",
  "term",
  "test",
  "unwind",
}